#include "_myheads.h"

QString CALC_POS2STR[CALC_POS_TYPE::NUM_CALC_POS] =
{
    METHOD_FULL_CENTROID_STR,
    METHOD_SUB_LS_STR,
    METHOD_TWO_CENTER_STR,
    METHOD_TAYLOR_SERIES_STR
};

QString TRACK_METHOD2STR[TRACK_METHOD::NUM_TRACK_METHOD] =
{
    METHOD_KALMAN_STR,
    METHOD_KALMAN_LITE_STR
};
